import re
import webbrowser
import os
import time
from datetime import datetime

# ==========================================
# PART 1: THE KNOWLEDGE BASE (Smart Rules)
# ==========================================
# We use Regex (Regular Expressions) for advanced pattern matching
SAFE_DOMAINS = [r".*\@company\.com$", r".*\@partner\.net$"]

# Rules: (Regex Pattern, Risk Score, Description)
THREAT_PATTERNS = [
    (r"(?i)\b(urgent|immediate|24 hours)\b", 15, "Urgency Trigger"),
    (r"(?i)\b(password|credential|login)\b", 25, "Credential Harvesting"),
    (r"(?i)\b(bank|transfer|invoice|payment)\b", 20, "Financial Pretext"),
    (r"(?i)\b(winner|inheritance|lottery)\b", 50, "Scam Context"),
    (r"http[s]?://", 10, "External Hyperlink"),
    (r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b", 50, "Raw IP Address (High Risk)")
]

BLOCK_THRESHOLD = 40

# ==========================================
# PART 2: THE INFERENCE ENGINE (The Brain)
# ==========================================
def analyze_email(sender, subject, body):
    score = 0
    triggers = []
    
    # 1. Sender Verification
    is_safe = any(re.match(pattern, sender) for pattern in SAFE_DOMAINS)
    if not is_safe:
        score += 20
        triggers.append("External Sender / Non-Whitelisted")
    
    # 2. Payload Analysis (Regex Scanning)
    full_text = f"{subject} {body}"
    for pattern, weight, description in THREAT_PATTERNS:
        matches = re.findall(pattern, full_text)
        if matches:
            count = len(matches)
            total_weight = weight * count
            score += total_weight
            triggers.append(f"{description} (Found {count}x) - (+{total_weight})")

    # 3. Decision Logic
    if score >= BLOCK_THRESHOLD:
        status = "BLOCKED"
        color = "#ffcccc" # Red for Report
    elif score >= 20:
        status = "FLAGGED"
        color = "#fff4cc" # Yellow for Report
    else:
        status = "ALLOWED"
        color = "#ccffcc" # Green for Report

    return {
        "timestamp": datetime.now().strftime("%H:%M:%S"),
        "sender": sender,
        "subject": subject,
        "score": score,
        "status": status,
        "triggers": ", ".join(triggers) if triggers else "None",
        "color": color
    }

# ==========================================
# PART 3: THE VISUALIZER (HTML Report Generator)
# ==========================================
def generate_report(results):
    html = f"""
    <html>
    <head>
        <title>AI Security Forensic Report</title>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; padding: 20px; background: #f4f4f9; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 10px; }}
            table {{ width: 100%; border-collapse: collapse; background: white; box-shadow: 0 5px 15px rgba(0,0,0,0.1); }}
            th {{ background: #2c3e50; color: white; padding: 12px; text-align: left; }}
            td {{ padding: 12px; border-bottom: 1px solid #ddd; }}
            tr:hover {{ background-color: #f1f1f1; }}
            .footer {{ margin-top: 20px; color: #777; font-size: 0.9em; }}
        </style>
    </head>
    <body>
        <h1>🛡️ AI Threat Analysis Log</h1>
        <table>
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Status</th>
                    <th>Risk Score</th>
                    <th>Sender</th>
                    <th>Reasoning (Triggers)</th>
                </tr>
            </thead>
            <tbody>
    """
    
    for row in results:
        html += f"""
        <tr style="background-color: {row['color']}">
            <td>{row['timestamp']}</td>
            <td><strong>{row['status']}</strong></td>
            <td>{row['score']}/100</td>
            <td>{row['sender']}</td>
            <td>{row['triggers']}</td>
        </tr>
        """
        
    html += """
            </tbody>
        </table>
        <div class="footer">Generated by Python Heuristic Protocol v2.0</div>
    </body>
    </html>
    """
    
    filename = "security_report.html"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    return filename

# ==========================================
# PART 4: THE INTERACTIVE SESSION (The Demo)
# ==========================================
def run_session():
    print("\n>>> INITIALIZING THREAT DETECTION PROTOCOL...")
    time.sleep(1)
    
    results = []
    
    # 1. Automated Batch (The "Baseline" Scan)
    print("\n--- [PHASE 1] SCANNING QUEUE ---")
    emails = [
        {"sender": "boss@company.com", "subject": "Meeting", "body": "3pm today?"},
        {"sender": "hacker@ru.com", "subject": "URGENT", "body": "Password expired. Click 192.168.1.1"}
    ]
    
    for email in emails:
        res = analyze_email(email['sender'], email['subject'], email['body'])
        results.append(res)
        print(f"Processed: {email['subject']} | Score: {res['score']}")
        time.sleep(0.5)

    # 2. THE INTERACTIVE PART (The "Hands-On" Scan)
    print("\n" + "="*40)
    print("      🛑 [PHASE 2] LIVE INTERACTIVE MODE 🛑")
    print("="*40)
    
    # This loop keeps asking until you type 'n'
    while True:
        choice = input("\nDo you want to test a custom email? (y/n): ").lower()
        if choice != 'y':
            break
            
        print("\n--- Enter Email Details ---")
        live_sender = input("Sender (e.g. unknown@site.com): ")
        live_subject = input("Subject: ")
        live_body = input("Body Text: ")
        
        print("\nScanning...")
        time.sleep(1) # Dramatic pause
        
        live_res = analyze_email(live_sender, live_subject, live_body)
        results.append(live_res)
        
        # Show immediate result in terminal
        print(f"RESULT: {live_res['status']} (Score: {live_res['score']})")
        print(f"Triggers: {live_res['triggers']}")

    # 3. Generate HTML Report
    print("\n--- [PHASE 3] GENERATING FORENSIC REPORT ---")
    report_file = generate_report(results)
    
    print(f"✅ Report saved: {report_file}")
    print("Opening in browser...")
    
    # Open Browser Automatically
    webbrowser.open('file://' + os.path.realpath(report_file))

if __name__ == "__main__":
    run_session()